---
name: Deploy to Heroku
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: pip

      - name: Install dependencies
        run: python -m pip install --upgrade pip poetry

      - name: Deploy to testpypi.org
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --build -r testpypi --username ${{ secrets.TESTPYPI_USERNAME }} --password ${{ secrets.TESTPYPI_PASSWORD }} || :

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "django-jazzmin"
          heroku_email: "${{secrets.HEROKU_EMAIL}}"
          appdir: tests/test_app
